### ISSUE TITLE
useEffect deps

### ISSUE THREAD

**Issue by SmileJayden** [juheeuu/h2ke-demo#1]
https://github.com/juheeuu/h2ke-demo/blob/2e8cfac59af061567974549e8710d7072fde5373/src/components/Views.js#L224

deps 없으면 rerender 일어날때마다 api 호출때려버리는 불상사가 일어납니다 형님

**Comment by juheeuu** [comment]
github  아이디 SmileJayden 인거 조금 킹받네요 ^^ 
조언 감사합니다

**Comment by juheeuu** [comment]
고쳤어용
